language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - ci/Gemfile-rails-4-0
  - ci/Gemfile-rails-4-1
  - ci/Gemfile-rails-4-2
  - ci/Gemfile-rails-5-0
  - ci/Gemfile-rails-5-1
  - ci/Gemfile-rails-5-2
  - ci/Gemfile-rails-6-0
matrix:
  exclude:
    - rvm: 2.4.6
      gemfile: ci/Gemfile-rails-4-0
    - rvm: 2.4.6
      gemfile: ci/Gemfile-rails-4-1
    - rvm: 2.4.6
      gemfile: ci/Gemfile-rails-6-0
    - rvm: 2.5.5
      gemfile: ci/Gemfile-rails-4-0
    - rvm: 2.5.5
      gemfile: ci/Gemfile-rails-4-1
    - rvm: 2.6.3
      gemfile: ci/Gemfile-rails-4-0
    - rvm: 2.6.3
      gemfile: ci/Gemfile-rails-4-1
before_install: gem update bundler
sudo: false
